services:
  frontend:
    image: emptycup-internshala-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    image: emptycup-internshala-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production

# services:
#   frontend:
#     image: emptycupacr.azurecr.io/emptycup/frontend:latest
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#   backend:
#     image: emptycupacr.azurecr.io/emptycup/backend:latest
#     ports:
#       - "5000:5000"
#     volumes:
#       - ${WEBAPP_STORAGE_HOME}/data:/app/data
#     environment:
#       - FLASK_ENV=production